language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran"
before_install:
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- no_open_mp ;
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- travis_wait 100 R CMD INSTALL --build ${PKG_TARBALL}
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: CTuYVOioyJGC/TdWq4GohSzq8umSFagJ+MdwF+3K3wAWDEGXPjVniKyS+wBEjL54100MIPnMsVhabgJ0uIcbmKNW7EL9xA24oo5P2hgj5pizWAdqn8EhUjbr2HJJ7Zlr7kERY0eEel0vy9fTls8gVLC+v1sYxNCQBnT0qWGBpNbKY7FRgJ/rmYDuIlRa4uSQqLCE/lEhb683zXOsGRtlMPgcPqXPNitXL47zJv6qshZJx+HgkjzXhFf2awGdmwhtQKs12RCwhxTpcrQJgZ+MGCCXwe3IS5wlkRRXK3qMTQDnC95leQf66oQFGogW5vrGAVkDTYwZig5WZOGbyHjNaWCVfRAZy7tnQyWcM8cPubb0Ym8bJ+uv4AvGbZM0dJXDVJd1fkggFCgxYjX8dkE8edt6D5RGpdDBbZsyO/fHup1suvafy7yqtgejbCq7x762NvGasXTZB4wbXQF7unK1HaEXp6Lx/RaVWRsflcyr15U1eu4AS5UGWz8DkwGq4eXs2IeFeRwj+DmgTXDZPpD80ysrDzTxYJs8nmkbhkXvUPk0nwcGlN5cwwmegFdN7j8kIVv3UIqM/Llz3LqbZo40BRGsnUWvHx9cdiKjqrHLQ27MuTzQbrtfgVI5I5+oo3bnOsPBDLADwoGKdw9VZKdpAoFcF0ftqHWdQbrCw6r5/WA=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then Rscript -e 'covr::coveralls(type =
  "all")' ; fi
