language: r
sudo: false
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
os:
- linux
- osx
osx_image: xcode9
dist: trusty
r:
- 3.2
- 3.3
- 3.4
- release
- devel
allow_failures:
- r: devel
- os: osx
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=neuroconductor
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- start_xvfb ;
- export rver=`r_version`;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- Rscript -e 'source("https://install-github.me/mangothecat/callr")'
- jags_install
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- if [[ "${PACKAGE_NAME}" == "waveslim" ]]; then fftw_install ; fi
- if [[ "${PACKAGE_NAME}" == "dti" ]]; then gsl_install ; fi
- if [[ "${PACKAGE_NAME}" == "ROpenCVLite" || "${PACKAGE_NAME}" == "Rvision" ]]; then
  shopt -s expand_aliases ; x=`Rscript -e "cat(Sys.which('R'))"` ; alias R="travis_wait
  100 ${x}" ; fi
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: WEOyh+KllHCLfd5vtw/RDYjLVDDXXxeROkm6eQijTlJM/Kn8QUjWRwmPI8llEqykoNt4u1YZ6CkgJOjkNzijUcNKWHl66M2D4C+AjkJ+2THm20yyT6SeM+BNVEGPaEFInt0pzMKe48Kgjn9iepS1LOpyyM6cR2AKpzDmb32goPSF6YxKBM17AjRCJE7M0CSl77jvIid4sd2FD1lJQGTKMlV9oL2clvxjmN7KFMEXRlpusxE57ChBA9oXHUpbHU6iNse0GA6c9qNDXvouadN7wtb7cYht4qgkgvrz0XWgg4SVggLcsv3bn54IRDm++6mAHSc9C02EoG218Tt0s/IjJOjEi3N4v11tBvgUM3J8D9JhYrTmZVdgf4b9wVsUVjHWGge93tQtJ2fbD3kaBZOe9tiZqp6ugCR2wZAT+G3Vk6Wakz/3UAXhyXPAH7tjyxWn56Jz+WOKATVRNpyMkLsq/TyAxipFVqoXKZb2V9oGmUfM8riKbTwU8kKY0fRPBmLhS1JuTl2Ub5RAwydzyBqx/wtdCOuGkM4UOkeeGUL0TMzFj44AEg1BWwf0+7vnQn8YkVoSfNtKlsz7msi2edXW+L6qb0bJ/gWgB8wTk5aqFDsLEQuNSQE9yHc1G33QEAsmtmfWqmKxZY4reXCRVw/doStbaLBz4GAhLRh4kKXQoJM=
after_deploy:
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" ]];
  then echo 'covr::coveralls(type = "all")' > neuroc_covr.R ; travis_wait 100 Rscript
  neuroc_covr.R ; rm neuroc_covr.R ; fi
